### ISSUE TITLE
Campo de seleção do tipo aparecendo em outras abas

### ISSUE THREAD

**Issue by ronnyjohnti** [secultce/plugin-EditOpportunityType#3]
## **Contexto**
- O campo de seleção aparece em todas as abas da oportunidade e fora do lugar.

## **Objetivo**
**Como** dev ou
**Quero** alterar o ponto de renderização do campo de seleção
**Para** que o mesmo só seja exibido na aba de configuração da avaliação.

## **Escopo**
- [x] Alterar hook utilizado para renderização.

## **Fora de Escopo**
- fora_de_escopo

## **Critérios de Aceitação**

- [x] Visualização do campo de seleção na aba correta
**Dado que** estou logado no Mapas Culturais
**E** estou na página de uma oportunidade documental cujo sou administrador 
**Quando** eu estiver editando a oportunidade
**Então** o campo para alterar o tipo só aparece na aba de configuração da avaliação.

# Observações

**Comment by Yasminemaciel02** [comment]
Fechado após teste
